name: Actualizar Lista M3U

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

# Esto da permiso explícito para que el script pueda subir el archivo .m3u
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4 # Actualizado para evitar el warning de Node

    - name: Configurar Python
      uses: actions/setup-python@v5 # Actualizado para evitar el warning de Node
      with:
        python-version: '3.11'

    - name: Instalar yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Ejecutar script
      run: python update_playlist.py

    - name: Guardar cambios en GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add lista_total.m3u
        # El comando || exit 0 evita que el workflow falle si no hay cambios en la lista
        git commit -m "Lista actualizada $(date)" || exit 0
        git push
