name: Actualizar Lista M3U

on:
  schedule:
    # Se ejecuta cada 6 horas automáticamente
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar yt-dlp actualizado
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp

    - name: Ejecutar script de unificación
      run: python update_playlist.py

    - name: Guardar y subir cambios
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add lista_total.m3u
        # El || exit 0 evita errores si no hay cambios en la lista
        git commit -m "Lista actualizada: $(date)" || exit 0
        git push
